# This file was generated by GoReleaser. DO NOT EDIT.
class Gurnel < Formula
  desc "Daily journaling for hackers"
  homepage "https://github.com/mikeraimondi/gurnel"
  url "https://github.com/mikeraimondi/gurnel/releases/download/v1.0.1/gurnel_1.0.1_Darwin_x86_64.tar.gz"
  version "1.0.1"
  sha256 "6a56b20b819cdd8c6357470d6c87f538c31dac8088e14e4f144a00957eafbcab"
  
  depends_on "git"

  def install
    bin.install "gurnel"
  end
end
