# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gurnel < Formula
  desc "Daily journaling for hackers"
  homepage "https://github.com/mikeraimondi/gurnel"
  version "1.2.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mikeraimondi/gurnel/releases/download/v1.2.3/gurnel_1.2.3_darwin_arm64.tar.gz"
      sha256 "9de7e3de1d9a9fb533d54cae9f3d0e3721966b9c79d1417466a81e8058f86365"

      def install
        bin.install "gurnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mikeraimondi/gurnel/releases/download/v1.2.3/gurnel_1.2.3_darwin_amd64.tar.gz"
      sha256 "ba3081d83080735c011bfefc5a6d41688fa6258bf9f989f32c672b48e5e3ac28"

      def install
        bin.install "gurnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mikeraimondi/gurnel/releases/download/v1.2.3/gurnel_1.2.3_linux_amd64.tar.gz"
      sha256 "7fd86511e6c9675618bb3d8ead695056efcc3c087cd6fce566d6bba761b6302e"

      def install
        bin.install "gurnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikeraimondi/gurnel/releases/download/v1.2.3/gurnel_1.2.3_linux_arm64.tar.gz"
      sha256 "d76e0f2d10e57f58410dad1780605e9c41f85291214d3a612a2bde302d85fc4c"

      def install
        bin.install "gurnel"
      end
    end
  end

  depends_on "git"
end
